/*
 * generated by Xtext 2.21.0
 */
package org.aedit.ui.tests;

import com.google.inject.Injector;
import org.aedit.ui.internal.AeditActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class AeditUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AeditActivator.getInstance().getInjector("org.aedit.Aedit");
	}

}
