/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotated Types</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aedit.aedit.AnnotatedTypes#getAnnotataions <em>Annotataions</em>}</li>
 *   <li>{@link org.aedit.aedit.AnnotatedTypes#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.aedit.aedit.AeditPackage#getAnnotatedTypes()
 * @model
 * @generated
 */
public interface AnnotatedTypes extends EObject
{
  /**
   * Returns the value of the '<em><b>Annotataions</b></em>' containment reference list.
   * The list contents are of type {@link org.aedit.aedit.Annotation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotataions</em>' containment reference list.
   * @see org.aedit.aedit.AeditPackage#getAnnotatedTypes_Annotataions()
   * @model containment="true"
   * @generated
   */
  EList<Annotation> getAnnotataions();

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Types)
   * @see org.aedit.aedit.AeditPackage#getAnnotatedTypes_Type()
   * @model containment="true"
   * @generated
   */
  Types getType();

  /**
   * Sets the value of the '{@link org.aedit.aedit.AnnotatedTypes#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Types value);

} // AnnotatedTypes
