/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit;

import avroclipse.avroIDL.Type;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Change Schema</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aedit.aedit.ChangeSchema#getSchemaType <em>Schema Type</em>}</li>
 *   <li>{@link org.aedit.aedit.ChangeSchema#getSchema <em>Schema</em>}</li>
 *   <li>{@link org.aedit.aedit.ChangeSchema#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see org.aedit.aedit.AeditPackage#getChangeSchema()
 * @model
 * @generated
 */
public interface ChangeSchema extends GenericRule
{
  /**
   * Returns the value of the '<em><b>Schema Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schema Type</em>' attribute.
   * @see #setSchemaType(String)
   * @see org.aedit.aedit.AeditPackage#getChangeSchema_SchemaType()
   * @model
   * @generated
   */
  String getSchemaType();

  /**
   * Sets the value of the '{@link org.aedit.aedit.ChangeSchema#getSchemaType <em>Schema Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schema Type</em>' attribute.
   * @see #getSchemaType()
   * @generated
   */
  void setSchemaType(String value);

  /**
   * Returns the value of the '<em><b>Schema</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schema</em>' reference.
   * @see #setSchema(Type)
   * @see org.aedit.aedit.AeditPackage#getChangeSchema_Schema()
   * @model
   * @generated
   */
  Type getSchema();

  /**
   * Sets the value of the '{@link org.aedit.aedit.ChangeSchema#getSchema <em>Schema</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schema</em>' reference.
   * @see #getSchema()
   * @generated
   */
  void setSchema(Type value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.aedit.aedit.SchemaRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see org.aedit.aedit.AeditPackage#getChangeSchema_Rules()
   * @model containment="true"
   * @generated
   */
  EList<SchemaRule> getRules();

} // ChangeSchema
