/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aedit.aedit.Feature#getName <em>Name</em>}</li>
 *   <li>{@link org.aedit.aedit.Feature#getExtend <em>Extend</em>}</li>
 *   <li>{@link org.aedit.aedit.Feature#getRuleMaps <em>Rule Maps</em>}</li>
 * </ul>
 *
 * @see org.aedit.aedit.AeditPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.aedit.aedit.AeditPackage#getFeature_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.aedit.aedit.Feature#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Extend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extend</em>' reference.
   * @see #setExtend(Feature)
   * @see org.aedit.aedit.AeditPackage#getFeature_Extend()
   * @model
   * @generated
   */
  Feature getExtend();

  /**
   * Sets the value of the '{@link org.aedit.aedit.Feature#getExtend <em>Extend</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extend</em>' reference.
   * @see #getExtend()
   * @generated
   */
  void setExtend(Feature value);

  /**
   * Returns the value of the '<em><b>Rule Maps</b></em>' reference list.
   * The list contents are of type {@link org.aedit.aedit.RuleMap}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule Maps</em>' reference list.
   * @see org.aedit.aedit.AeditPackage#getFeature_RuleMaps()
   * @model
   * @generated
   */
  EList<RuleMap> getRuleMaps();

} // Feature
