/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aedit.aedit.FeatureMap#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.aedit.aedit.AeditPackage#getFeatureMap()
 * @model
 * @generated
 */
public interface FeatureMap extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(Feature)
   * @see org.aedit.aedit.AeditPackage#getFeatureMap_Name()
   * @model
   * @generated
   */
  Feature getName();

  /**
   * Sets the value of the '{@link org.aedit.aedit.FeatureMap#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(Feature value);

} // FeatureMap
