/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Float Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aedit.aedit.FloatValue#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see org.aedit.aedit.AeditPackage#getFloatValue()
 * @model
 * @generated
 */
public interface FloatValue extends Value
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(float)
   * @see org.aedit.aedit.AeditPackage#getFloatValue_Val()
   * @model
   * @generated
   */
  float getVal();

  /**
   * Sets the value of the '{@link org.aedit.aedit.FloatValue#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(float value);

} // FloatValue
