/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit;

import avroclipse.avroIDL.Annotation;
import avroclipse.avroIDL.Field;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Remove Annotation From Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.aedit.aedit.RemoveAnnotationFromField#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.aedit.aedit.RemoveAnnotationFromField#getAnnotationToRemove <em>Annotation To Remove</em>}</li>
 * </ul>
 *
 * @see org.aedit.aedit.AeditPackage#getRemoveAnnotationFromField()
 * @model
 * @generated
 */
public interface RemoveAnnotationFromField extends SchemaRule
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(Field)
   * @see org.aedit.aedit.AeditPackage#getRemoveAnnotationFromField_Variable()
   * @model
   * @generated
   */
  Field getVariable();

  /**
   * Sets the value of the '{@link org.aedit.aedit.RemoveAnnotationFromField#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Field value);

  /**
   * Returns the value of the '<em><b>Annotation To Remove</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotation To Remove</em>' reference.
   * @see #setAnnotationToRemove(Annotation)
   * @see org.aedit.aedit.AeditPackage#getRemoveAnnotationFromField_AnnotationToRemove()
   * @model
   * @generated
   */
  Annotation getAnnotationToRemove();

  /**
   * Sets the value of the '{@link org.aedit.aedit.RemoveAnnotationFromField#getAnnotationToRemove <em>Annotation To Remove</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Annotation To Remove</em>' reference.
   * @see #getAnnotationToRemove()
   * @generated
   */
  void setAnnotationToRemove(Annotation value);

} // RemoveAnnotationFromField
