/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit.impl;

import java.util.Collection;

import org.aedit.aedit.AeditPackage;
import org.aedit.aedit.AnnotatedTypes;
import org.aedit.aedit.Annotation;
import org.aedit.aedit.Types;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Annotated Types</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.aedit.aedit.impl.AnnotatedTypesImpl#getAnnotataions <em>Annotataions</em>}</li>
 *   <li>{@link org.aedit.aedit.impl.AnnotatedTypesImpl#getType <em>Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AnnotatedTypesImpl extends MinimalEObjectImpl.Container implements AnnotatedTypes
{
  /**
   * The cached value of the '{@link #getAnnotataions() <em>Annotataions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnotataions()
   * @generated
   * @ordered
   */
  protected EList<Annotation> annotataions;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected Types type;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AnnotatedTypesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AeditPackage.Literals.ANNOTATED_TYPES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Annotation> getAnnotataions()
  {
    if (annotataions == null)
    {
      annotataions = new EObjectContainmentEList<Annotation>(Annotation.class, this, AeditPackage.ANNOTATED_TYPES__ANNOTATAIONS);
    }
    return annotataions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Types getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(Types newType, NotificationChain msgs)
  {
    Types oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AeditPackage.ANNOTATED_TYPES__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(Types newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AeditPackage.ANNOTATED_TYPES__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AeditPackage.ANNOTATED_TYPES__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AeditPackage.ANNOTATED_TYPES__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AeditPackage.ANNOTATED_TYPES__ANNOTATAIONS:
        return ((InternalEList<?>)getAnnotataions()).basicRemove(otherEnd, msgs);
      case AeditPackage.ANNOTATED_TYPES__TYPE:
        return basicSetType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AeditPackage.ANNOTATED_TYPES__ANNOTATAIONS:
        return getAnnotataions();
      case AeditPackage.ANNOTATED_TYPES__TYPE:
        return getType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AeditPackage.ANNOTATED_TYPES__ANNOTATAIONS:
        getAnnotataions().clear();
        getAnnotataions().addAll((Collection<? extends Annotation>)newValue);
        return;
      case AeditPackage.ANNOTATED_TYPES__TYPE:
        setType((Types)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AeditPackage.ANNOTATED_TYPES__ANNOTATAIONS:
        getAnnotataions().clear();
        return;
      case AeditPackage.ANNOTATED_TYPES__TYPE:
        setType((Types)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AeditPackage.ANNOTATED_TYPES__ANNOTATAIONS:
        return annotataions != null && !annotataions.isEmpty();
      case AeditPackage.ANNOTATED_TYPES__TYPE:
        return type != null;
    }
    return super.eIsSet(featureID);
  }

} //AnnotatedTypesImpl
