/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit.impl;

import org.aedit.aedit.AeditPackage;
import org.aedit.aedit.ArrayEditRules;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Array Edit Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ArrayEditRulesImpl extends SchemaRuleImpl implements ArrayEditRules
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ArrayEditRulesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AeditPackage.Literals.ARRAY_EDIT_RULES;
  }

} //ArrayEditRulesImpl
