/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit.impl;

import org.aedit.aedit.AeditPackage;
import org.aedit.aedit.GenericRule;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Generic Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GenericRuleImpl extends MinimalEObjectImpl.Container implements GenericRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GenericRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AeditPackage.Literals.GENERIC_RULE;
  }

} //GenericRuleImpl
