/**
 * generated by Xtext 2.21.0
 */
package org.aedit.aedit.impl;

import avroclipse.avroIDL.Annotation;
import avroclipse.avroIDL.Type;

import org.aedit.aedit.AeditPackage;
import org.aedit.aedit.RemoveAnnotationFromSchema;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Remove Annotation From Schema</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.aedit.aedit.impl.RemoveAnnotationFromSchemaImpl#getSchemaType <em>Schema Type</em>}</li>
 *   <li>{@link org.aedit.aedit.impl.RemoveAnnotationFromSchemaImpl#getSchema <em>Schema</em>}</li>
 *   <li>{@link org.aedit.aedit.impl.RemoveAnnotationFromSchemaImpl#getAnnotationToRemove <em>Annotation To Remove</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RemoveAnnotationFromSchemaImpl extends GenericRuleImpl implements RemoveAnnotationFromSchema
{
  /**
   * The default value of the '{@link #getSchemaType() <em>Schema Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchemaType()
   * @generated
   * @ordered
   */
  protected static final String SCHEMA_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSchemaType() <em>Schema Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchemaType()
   * @generated
   * @ordered
   */
  protected String schemaType = SCHEMA_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getSchema() <em>Schema</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchema()
   * @generated
   * @ordered
   */
  protected Type schema;

  /**
   * The cached value of the '{@link #getAnnotationToRemove() <em>Annotation To Remove</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnotationToRemove()
   * @generated
   * @ordered
   */
  protected Annotation annotationToRemove;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RemoveAnnotationFromSchemaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AeditPackage.Literals.REMOVE_ANNOTATION_FROM_SCHEMA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSchemaType()
  {
    return schemaType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSchemaType(String newSchemaType)
  {
    String oldSchemaType = schemaType;
    schemaType = newSchemaType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA_TYPE, oldSchemaType, schemaType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Type getSchema()
  {
    if (schema != null && schema.eIsProxy())
    {
      InternalEObject oldSchema = (InternalEObject)schema;
      schema = (Type)eResolveProxy(oldSchema);
      if (schema != oldSchema)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA, oldSchema, schema));
      }
    }
    return schema;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type basicGetSchema()
  {
    return schema;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSchema(Type newSchema)
  {
    Type oldSchema = schema;
    schema = newSchema;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA, oldSchema, schema));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Annotation getAnnotationToRemove()
  {
    if (annotationToRemove != null && annotationToRemove.eIsProxy())
    {
      InternalEObject oldAnnotationToRemove = (InternalEObject)annotationToRemove;
      annotationToRemove = (Annotation)eResolveProxy(oldAnnotationToRemove);
      if (annotationToRemove != oldAnnotationToRemove)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__ANNOTATION_TO_REMOVE, oldAnnotationToRemove, annotationToRemove));
      }
    }
    return annotationToRemove;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Annotation basicGetAnnotationToRemove()
  {
    return annotationToRemove;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAnnotationToRemove(Annotation newAnnotationToRemove)
  {
    Annotation oldAnnotationToRemove = annotationToRemove;
    annotationToRemove = newAnnotationToRemove;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__ANNOTATION_TO_REMOVE, oldAnnotationToRemove, annotationToRemove));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA_TYPE:
        return getSchemaType();
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA:
        if (resolve) return getSchema();
        return basicGetSchema();
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__ANNOTATION_TO_REMOVE:
        if (resolve) return getAnnotationToRemove();
        return basicGetAnnotationToRemove();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA_TYPE:
        setSchemaType((String)newValue);
        return;
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA:
        setSchema((Type)newValue);
        return;
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__ANNOTATION_TO_REMOVE:
        setAnnotationToRemove((Annotation)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA_TYPE:
        setSchemaType(SCHEMA_TYPE_EDEFAULT);
        return;
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA:
        setSchema((Type)null);
        return;
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__ANNOTATION_TO_REMOVE:
        setAnnotationToRemove((Annotation)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA_TYPE:
        return SCHEMA_TYPE_EDEFAULT == null ? schemaType != null : !SCHEMA_TYPE_EDEFAULT.equals(schemaType);
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__SCHEMA:
        return schema != null;
      case AeditPackage.REMOVE_ANNOTATION_FROM_SCHEMA__ANNOTATION_TO_REMOVE:
        return annotationToRemove != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (schemaType: ");
    result.append(schemaType);
    result.append(')');
    return result.toString();
  }

} //RemoveAnnotationFromSchemaImpl
