/*
 * generated by Xtext 2.21.0
 */
package org.aedit.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.aedit.ide.contentassist.antlr.internal.InternalAeditParser;
import org.aedit.services.AeditGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AeditParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AeditGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AeditGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getGenericRuleAccess().getAlternatives(), "rule__GenericRule__Alternatives");
			builder.put(grammarAccess.getSchemaRuleAccess().getAlternatives(), "rule__SchemaRule__Alternatives");
			builder.put(grammarAccess.getArrayEditRulesAccess().getAlternatives(), "rule__ArrayEditRules__Alternatives");
			builder.put(grammarAccess.getEnumRuleAccess().getAlternatives(), "rule__EnumRule__Alternatives");
			builder.put(grammarAccess.getChangeSchemaAccess().getSchemaTypeAlternatives_1_0(), "rule__ChangeSchema__SchemaTypeAlternatives_1_0");
			builder.put(grammarAccess.getAddAccess().getAlternatives(), "rule__Add__Alternatives");
			builder.put(grammarAccess.getAddValueToArrayAccess().getValueToAddAlternatives_6_0(), "rule__AddValueToArray__ValueToAddAlternatives_6_0");
			builder.put(grammarAccess.getFieldAccess().getFieldTypeAlternatives_1_0(), "rule__Field__FieldTypeAlternatives_1_0");
			builder.put(grammarAccess.getTypesAccess().getAlternatives(), "rule__Types__Alternatives");
			builder.put(grammarAccess.getValuesAccess().getAlternatives_1(), "rule__Values__Alternatives_1");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getIntValueAccess().getValAlternatives_0(), "rule__IntValue__ValAlternatives_0");
			builder.put(grammarAccess.getBooleanAccess().getAlternatives(), "rule__Boolean__Alternatives");
			builder.put(grammarAccess.getSCHEMA_TYPEAccess().getAlternatives(), "rule__SCHEMA_TYPE__Alternatives");
			builder.put(grammarAccess.getVARIABLE_TYPEAccess().getAlternatives(), "rule__VARIABLE_TYPE__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup(), "rule__Feature__Group__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_2(), "rule__Feature__Group_2__0");
			builder.put(grammarAccess.getFeatureMapAccess().getGroup(), "rule__FeatureMap__Group__0");
			builder.put(grammarAccess.getRuleMapAccess().getGroup(), "rule__RuleMap__Group__0");
			builder.put(grammarAccess.getRuleDeclarationAccess().getGroup(), "rule__RuleDeclaration__Group__0");
			builder.put(grammarAccess.getAddAnnotationToSchemaAccess().getGroup(), "rule__AddAnnotationToSchema__Group__0");
			builder.put(grammarAccess.getAddAnnotationToFieldAccess().getGroup(), "rule__AddAnnotationToField__Group__0");
			builder.put(grammarAccess.getAddNameAnnotationToFieldAccess().getGroup(), "rule__AddNameAnnotationToField__Group__0");
			builder.put(grammarAccess.getRemoveAnnotationFromSchemaAccess().getGroup(), "rule__RemoveAnnotationFromSchema__Group__0");
			builder.put(grammarAccess.getRemoveAnnotationFromFieldAccess().getGroup(), "rule__RemoveAnnotationFromField__Group__0");
			builder.put(grammarAccess.getRemoveNameAnnotationFromFieldAccess().getGroup(), "rule__RemoveNameAnnotationFromField__Group__0");
			builder.put(grammarAccess.getChangeSchemaAccess().getGroup(), "rule__ChangeSchema__Group__0");
			builder.put(grammarAccess.getChangeEnumAccess().getGroup(), "rule__ChangeEnum__Group__0");
			builder.put(grammarAccess.getAddRecordAccess().getGroup(), "rule__AddRecord__Group__0");
			builder.put(grammarAccess.getAddErrorAccess().getGroup(), "rule__AddError__Group__0");
			builder.put(grammarAccess.getAddEnumerationAccess().getGroup(), "rule__AddEnumeration__Group__0");
			builder.put(grammarAccess.getAddEnumerationAccess().getGroup_10(), "rule__AddEnumeration__Group_10__0");
			builder.put(grammarAccess.getAddVariableAccess().getGroup(), "rule__AddVariable__Group__0");
			builder.put(grammarAccess.getAddEnumAccess().getGroup(), "rule__AddEnum__Group__0");
			builder.put(grammarAccess.getRemoveSchemaAccess().getGroup(), "rule__RemoveSchema__Group__0");
			builder.put(grammarAccess.getRemoveVariableAccess().getGroup(), "rule__RemoveVariable__Group__0");
			builder.put(grammarAccess.getRemoveEnumAccess().getGroup(), "rule__RemoveEnum__Group__0");
			builder.put(grammarAccess.getRenameSchemaAccess().getGroup(), "rule__RenameSchema__Group__0");
			builder.put(grammarAccess.getRenameVariableAccess().getGroup(), "rule__RenameVariable__Group__0");
			builder.put(grammarAccess.getRenameEnumAccess().getGroup(), "rule__RenameEnum__Group__0");
			builder.put(grammarAccess.getChangeDefValueAccess().getGroup(), "rule__ChangeDefValue__Group__0");
			builder.put(grammarAccess.getChangeTypeAccess().getGroup(), "rule__ChangeType__Group__0");
			builder.put(grammarAccess.getRemoveArrayValueAccess().getGroup(), "rule__RemoveArrayValue__Group__0");
			builder.put(grammarAccess.getRemoveArrayValueAtIndexAccess().getGroup(), "rule__RemoveArrayValueAtIndex__Group__0");
			builder.put(grammarAccess.getAddValueToArrayAccess().getGroup(), "rule__AddValueToArray__Group__0");
			builder.put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
			builder.put(grammarAccess.getCustomTypeFieldAccess().getGroup(), "rule__CustomTypeField__Group__0");
			builder.put(grammarAccess.getPrimitiveTypeFieldAccess().getGroup(), "rule__PrimitiveTypeField__Group__0");
			builder.put(grammarAccess.getPrimitiveTypeFieldAccess().getGroup_3(), "rule__PrimitiveTypeField__Group_3__0");
			builder.put(grammarAccess.getComplexTypeFieldAccess().getGroup(), "rule__ComplexTypeField__Group__0");
			builder.put(grammarAccess.getComplexTypeFieldAccess().getGroup_3(), "rule__ComplexTypeField__Group_3__0");
			builder.put(grammarAccess.getArrayTypeFieldAccess().getGroup(), "rule__ArrayTypeField__Group__0");
			builder.put(grammarAccess.getAnnotatedTypesAccess().getGroup(), "rule__AnnotatedTypes__Group__0");
			builder.put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
			builder.put(grammarAccess.getAnnotationAccess().getGroup_1(), "rule__Annotation__Group_1__0");
			builder.put(grammarAccess.getValuesAccess().getGroup(), "rule__Values__Group__0");
			builder.put(grammarAccess.getValuesAccess().getGroup_1_1(), "rule__Values__Group_1_1__0");
			builder.put(grammarAccess.getValuesAccess().getGroup_1_1_1(), "rule__Values__Group_1_1_1__0");
			builder.put(grammarAccess.getArrayAccess().getGroup(), "rule__Array__Group__0");
			builder.put(grammarAccess.getRealAccess().getGroup(), "rule__Real__Group__0");
			builder.put(grammarAccess.getNegativeIntAccess().getGroup(), "rule__NegativeInt__Group__0");
			builder.put(grammarAccess.getQNAccess().getGroup(), "rule__QN__Group__0");
			builder.put(grammarAccess.getQNAccess().getGroup_1(), "rule__QN__Group_1__0");
			builder.put(grammarAccess.getANAccess().getGroup(), "rule__AN__Group__0");
			builder.put(grammarAccess.getANAccess().getGroup_2(), "rule__AN__Group_2__0");
			builder.put(grammarAccess.getModelAccess().getRuleDeclarationsAssignment_0(), "rule__Model__RuleDeclarationsAssignment_0");
			builder.put(grammarAccess.getModelAccess().getRuleMapsAssignment_1(), "rule__Model__RuleMapsAssignment_1");
			builder.put(grammarAccess.getModelAccess().getFeaturesAssignment_2(), "rule__Model__FeaturesAssignment_2");
			builder.put(grammarAccess.getModelAccess().getFeatureMapsAssignment_3(), "rule__Model__FeatureMapsAssignment_3");
			builder.put(grammarAccess.getFeatureAccess().getNameAssignment_1(), "rule__Feature__NameAssignment_1");
			builder.put(grammarAccess.getFeatureAccess().getExtendAssignment_2_1(), "rule__Feature__ExtendAssignment_2_1");
			builder.put(grammarAccess.getFeatureAccess().getRuleMapsAssignment_4(), "rule__Feature__RuleMapsAssignment_4");
			builder.put(grammarAccess.getFeatureMapAccess().getNameAssignment_1(), "rule__FeatureMap__NameAssignment_1");
			builder.put(grammarAccess.getRuleMapAccess().getNameAssignment_1(), "rule__RuleMap__NameAssignment_1");
			builder.put(grammarAccess.getRuleMapAccess().getRulesAssignment_3(), "rule__RuleMap__RulesAssignment_3");
			builder.put(grammarAccess.getRuleDeclarationAccess().getNameAssignment_1(), "rule__RuleDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getRuleDeclarationAccess().getRulesAssignment_3(), "rule__RuleDeclaration__RulesAssignment_3");
			builder.put(grammarAccess.getAddAnnotationToSchemaAccess().getSchemaTypeAssignment_1(), "rule__AddAnnotationToSchema__SchemaTypeAssignment_1");
			builder.put(grammarAccess.getAddAnnotationToSchemaAccess().getSchemaAssignment_2(), "rule__AddAnnotationToSchema__SchemaAssignment_2");
			builder.put(grammarAccess.getAddAnnotationToSchemaAccess().getAnnotationAssignment_4(), "rule__AddAnnotationToSchema__AnnotationAssignment_4");
			builder.put(grammarAccess.getAddAnnotationToFieldAccess().getVariableAssignment_1(), "rule__AddAnnotationToField__VariableAssignment_1");
			builder.put(grammarAccess.getAddAnnotationToFieldAccess().getAnnotationAssignment_3(), "rule__AddAnnotationToField__AnnotationAssignment_3");
			builder.put(grammarAccess.getAddNameAnnotationToFieldAccess().getVariableAssignment_1(), "rule__AddNameAnnotationToField__VariableAssignment_1");
			builder.put(grammarAccess.getAddNameAnnotationToFieldAccess().getAnnotationAssignment_3(), "rule__AddNameAnnotationToField__AnnotationAssignment_3");
			builder.put(grammarAccess.getRemoveAnnotationFromSchemaAccess().getSchemaTypeAssignment_1(), "rule__RemoveAnnotationFromSchema__SchemaTypeAssignment_1");
			builder.put(grammarAccess.getRemoveAnnotationFromSchemaAccess().getSchemaAssignment_2(), "rule__RemoveAnnotationFromSchema__SchemaAssignment_2");
			builder.put(grammarAccess.getRemoveAnnotationFromSchemaAccess().getAnnotationToRemoveAssignment_4(), "rule__RemoveAnnotationFromSchema__AnnotationToRemoveAssignment_4");
			builder.put(grammarAccess.getRemoveAnnotationFromFieldAccess().getVariableAssignment_1(), "rule__RemoveAnnotationFromField__VariableAssignment_1");
			builder.put(grammarAccess.getRemoveAnnotationFromFieldAccess().getAnnotationToRemoveAssignment_3(), "rule__RemoveAnnotationFromField__AnnotationToRemoveAssignment_3");
			builder.put(grammarAccess.getRemoveNameAnnotationFromFieldAccess().getVariableAssignment_1(), "rule__RemoveNameAnnotationFromField__VariableAssignment_1");
			builder.put(grammarAccess.getRemoveNameAnnotationFromFieldAccess().getAnnotationToRemoveAssignment_3(), "rule__RemoveNameAnnotationFromField__AnnotationToRemoveAssignment_3");
			builder.put(grammarAccess.getChangeSchemaAccess().getSchemaTypeAssignment_1(), "rule__ChangeSchema__SchemaTypeAssignment_1");
			builder.put(grammarAccess.getChangeSchemaAccess().getSchemaAssignment_2(), "rule__ChangeSchema__SchemaAssignment_2");
			builder.put(grammarAccess.getChangeSchemaAccess().getRulesAssignment_4(), "rule__ChangeSchema__RulesAssignment_4");
			builder.put(grammarAccess.getChangeEnumAccess().getSchemaAssignment_2(), "rule__ChangeEnum__SchemaAssignment_2");
			builder.put(grammarAccess.getChangeEnumAccess().getRulesAssignment_4(), "rule__ChangeEnum__RulesAssignment_4");
			builder.put(grammarAccess.getAddRecordAccess().getIndexAssignment_2(), "rule__AddRecord__IndexAssignment_2");
			builder.put(grammarAccess.getAddRecordAccess().getNamespaceAssignment_5(), "rule__AddRecord__NamespaceAssignment_5");
			builder.put(grammarAccess.getAddRecordAccess().getRecordNameAssignment_7(), "rule__AddRecord__RecordNameAssignment_7");
			builder.put(grammarAccess.getAddRecordAccess().getFieldsAssignment_9(), "rule__AddRecord__FieldsAssignment_9");
			builder.put(grammarAccess.getAddErrorAccess().getIndexAssignment_2(), "rule__AddError__IndexAssignment_2");
			builder.put(grammarAccess.getAddErrorAccess().getNamespaceAssignment_5(), "rule__AddError__NamespaceAssignment_5");
			builder.put(grammarAccess.getAddErrorAccess().getErrorNameAssignment_7(), "rule__AddError__ErrorNameAssignment_7");
			builder.put(grammarAccess.getAddErrorAccess().getFieldsAssignment_9(), "rule__AddError__FieldsAssignment_9");
			builder.put(grammarAccess.getAddEnumerationAccess().getIndexAssignment_2(), "rule__AddEnumeration__IndexAssignment_2");
			builder.put(grammarAccess.getAddEnumerationAccess().getNamespaceAssignment_5(), "rule__AddEnumeration__NamespaceAssignment_5");
			builder.put(grammarAccess.getAddEnumerationAccess().getEnumNameAssignment_7(), "rule__AddEnumeration__EnumNameAssignment_7");
			builder.put(grammarAccess.getAddEnumerationAccess().getSymbolsAssignment_9(), "rule__AddEnumeration__SymbolsAssignment_9");
			builder.put(grammarAccess.getAddEnumerationAccess().getSymbolsAssignment_10_1(), "rule__AddEnumeration__SymbolsAssignment_10_1");
			builder.put(grammarAccess.getAddVariableAccess().getIndexAssignment_2(), "rule__AddVariable__IndexAssignment_2");
			builder.put(grammarAccess.getAddVariableAccess().getNewVarAssignment_4(), "rule__AddVariable__NewVarAssignment_4");
			builder.put(grammarAccess.getAddEnumAccess().getIndexAssignment_2(), "rule__AddEnum__IndexAssignment_2");
			builder.put(grammarAccess.getAddEnumAccess().getVarNameAssignment_4(), "rule__AddEnum__VarNameAssignment_4");
			builder.put(grammarAccess.getRemoveSchemaAccess().getSchemaTypeAssignment_1(), "rule__RemoveSchema__SchemaTypeAssignment_1");
			builder.put(grammarAccess.getRemoveSchemaAccess().getSchemaAssignment_2(), "rule__RemoveSchema__SchemaAssignment_2");
			builder.put(grammarAccess.getRemoveVariableAccess().getVariableAssignment_1(), "rule__RemoveVariable__VariableAssignment_1");
			builder.put(grammarAccess.getRemoveEnumAccess().getVarNameAssignment_1(), "rule__RemoveEnum__VarNameAssignment_1");
			builder.put(grammarAccess.getRenameSchemaAccess().getSchemaTypeAssignment_1(), "rule__RenameSchema__SchemaTypeAssignment_1");
			builder.put(grammarAccess.getRenameSchemaAccess().getSchemaAssignment_2(), "rule__RenameSchema__SchemaAssignment_2");
			builder.put(grammarAccess.getRenameSchemaAccess().getNewSchNameAssignment_4(), "rule__RenameSchema__NewSchNameAssignment_4");
			builder.put(grammarAccess.getRenameVariableAccess().getVariableAssignment_1(), "rule__RenameVariable__VariableAssignment_1");
			builder.put(grammarAccess.getRenameVariableAccess().getNewVarNameAssignment_3(), "rule__RenameVariable__NewVarNameAssignment_3");
			builder.put(grammarAccess.getRenameEnumAccess().getOldNameAssignment_1(), "rule__RenameEnum__OldNameAssignment_1");
			builder.put(grammarAccess.getRenameEnumAccess().getNewEnumNameAssignment_3(), "rule__RenameEnum__NewEnumNameAssignment_3");
			builder.put(grammarAccess.getChangeDefValueAccess().getFieldAssignment_1(), "rule__ChangeDefValue__FieldAssignment_1");
			builder.put(grammarAccess.getChangeDefValueAccess().getNewValAssignment_3(), "rule__ChangeDefValue__NewValAssignment_3");
			builder.put(grammarAccess.getChangeTypeAccess().getFieldAssignment_1(), "rule__ChangeType__FieldAssignment_1");
			builder.put(grammarAccess.getChangeTypeAccess().getNewTypeAssignment_3(), "rule__ChangeType__NewTypeAssignment_3");
			builder.put(grammarAccess.getRemoveArrayValueAccess().getVariableAssignment_1(), "rule__RemoveArrayValue__VariableAssignment_1");
			builder.put(grammarAccess.getRemoveArrayValueAccess().getValueToRemoveAssignment_3(), "rule__RemoveArrayValue__ValueToRemoveAssignment_3");
			builder.put(grammarAccess.getRemoveArrayValueAtIndexAccess().getIndexAssignment_2(), "rule__RemoveArrayValueAtIndex__IndexAssignment_2");
			builder.put(grammarAccess.getRemoveArrayValueAtIndexAccess().getArrayAssignment_4(), "rule__RemoveArrayValueAtIndex__ArrayAssignment_4");
			builder.put(grammarAccess.getAddValueToArrayAccess().getIndexAssignment_2(), "rule__AddValueToArray__IndexAssignment_2");
			builder.put(grammarAccess.getAddValueToArrayAccess().getArrayAssignment_4(), "rule__AddValueToArray__ArrayAssignment_4");
			builder.put(grammarAccess.getAddValueToArrayAccess().getValueToAddAssignment_6(), "rule__AddValueToArray__ValueToAddAssignment_6");
			builder.put(grammarAccess.getFieldAccess().getAnnotationsAssignment_0(), "rule__Field__AnnotationsAssignment_0");
			builder.put(grammarAccess.getFieldAccess().getFieldTypeAssignment_1(), "rule__Field__FieldTypeAssignment_1");
			builder.put(grammarAccess.getCustomTypeFieldAccess().getTypeAssignment_0(), "rule__CustomTypeField__TypeAssignment_0");
			builder.put(grammarAccess.getCustomTypeFieldAccess().getNameAnnotationsAssignment_1(), "rule__CustomTypeField__NameAnnotationsAssignment_1");
			builder.put(grammarAccess.getCustomTypeFieldAccess().getVarNameAssignment_2(), "rule__CustomTypeField__VarNameAssignment_2");
			builder.put(grammarAccess.getPrimitiveTypeFieldAccess().getTypeAssignment_0(), "rule__PrimitiveTypeField__TypeAssignment_0");
			builder.put(grammarAccess.getPrimitiveTypeFieldAccess().getNameAnnotationsAssignment_1(), "rule__PrimitiveTypeField__NameAnnotationsAssignment_1");
			builder.put(grammarAccess.getPrimitiveTypeFieldAccess().getVarNameAssignment_2(), "rule__PrimitiveTypeField__VarNameAssignment_2");
			builder.put(grammarAccess.getPrimitiveTypeFieldAccess().getValueAssignment_3_1(), "rule__PrimitiveTypeField__ValueAssignment_3_1");
			builder.put(grammarAccess.getComplexTypeFieldAccess().getTypeAssignment_0(), "rule__ComplexTypeField__TypeAssignment_0");
			builder.put(grammarAccess.getComplexTypeFieldAccess().getNameAnnotationsAssignment_1(), "rule__ComplexTypeField__NameAnnotationsAssignment_1");
			builder.put(grammarAccess.getComplexTypeFieldAccess().getVarNameAssignment_2(), "rule__ComplexTypeField__VarNameAssignment_2");
			builder.put(grammarAccess.getComplexTypeFieldAccess().getValueAssignment_3_1(), "rule__ComplexTypeField__ValueAssignment_3_1");
			builder.put(grammarAccess.getArrayTypeFieldAccess().getTypeAssignment_2(), "rule__ArrayTypeField__TypeAssignment_2");
			builder.put(grammarAccess.getAnnotatedTypesAccess().getAnnotataionsAssignment_0(), "rule__AnnotatedTypes__AnnotataionsAssignment_0");
			builder.put(grammarAccess.getAnnotatedTypesAccess().getTypeAssignment_1(), "rule__AnnotatedTypes__TypeAssignment_1");
			builder.put(grammarAccess.getCustomTypeAccess().getTargetAssignment(), "rule__CustomType__TargetAssignment");
			builder.put(grammarAccess.getPrimitiveTypeAccess().getTargetAssignment(), "rule__PrimitiveType__TargetAssignment");
			builder.put(grammarAccess.getAnnotationAccess().getNameAssignment_0(), "rule__Annotation__NameAssignment_0");
			builder.put(grammarAccess.getAnnotationAccess().getValuesAssignment_1_1(), "rule__Annotation__ValuesAssignment_1_1");
			builder.put(grammarAccess.getValuesAccess().getValueAssignment_1_0(), "rule__Values__ValueAssignment_1_0");
			builder.put(grammarAccess.getValuesAccess().getValueAssignment_1_1_0(), "rule__Values__ValueAssignment_1_1_0");
			builder.put(grammarAccess.getValuesAccess().getValueAssignment_1_1_1_1(), "rule__Values__ValueAssignment_1_1_1_1");
			builder.put(grammarAccess.getArrayAccess().getValuesAssignment_1(), "rule__Array__ValuesAssignment_1");
			builder.put(grammarAccess.getFloatValueAccess().getValAssignment(), "rule__FloatValue__ValAssignment");
			builder.put(grammarAccess.getStringValueAccess().getValAssignment(), "rule__StringValue__ValAssignment");
			builder.put(grammarAccess.getIntValueAccess().getValAssignment(), "rule__IntValue__ValAssignment");
			builder.put(grammarAccess.getNullAccess().getValAssignment(), "rule__Null__ValAssignment");
			builder.put(grammarAccess.getBooleanValueAccess().getValAssignment(), "rule__BooleanValue__ValAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AeditGrammarAccess grammarAccess;

	@Override
	protected InternalAeditParser createParser() {
		InternalAeditParser result = new InternalAeditParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AeditGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AeditGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
