/*
 * generated by Xtext 2.12.0
 */
package org.aedit.tests

import com.google.inject.Inject
import javax.inject.Provider
import org.aedit.aedit.AeditPackage
import org.aedit.aedit.Model
import org.aedit.validation.ErrorCodes
import org.aedit.validation.ErrorMessages
import org.eclipse.emf.common.util.URI
import org.eclipse.emf.ecore.EClass
import org.eclipse.emf.ecore.resource.ResourceSet
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.eclipse.xtext.util.StringInputStream
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(AvroclipseProvider)
class AeditValidatorTest {

	@Inject extension ValidationTestHelper
	@Inject extension ParseHelper<Model>

	@Inject
	Provider<ResourceSet> rsp;

	@Test
	def void testRuleMapDeclaration__InvalidName(){
		parse('''
			ruleset RuleMap1 { }
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.ruleMap, ErrorCodes.RULE_MAP, ErrorMessages.INVALID_NAME)
	}
	
	@Test
	def void testRuleMapDeclaration__DuplicateName(){
		parse('''
			ruleset RuleSet1 { }
			ruleset RuleSet1 { }
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.ruleMap, ErrorCodes.DUPLICATE_FIELD, ErrorMessages.DUPLICATE_NAME)
	}

	@Test
	def void testRemoveSchema__DeletedSchema() {

		parse('''
			rule Rule1 {
						remove record house.Garage;
						remove record house.Garage;
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.removeSchema, ErrorCodes.REMOVE_SCHEMA, ErrorMessages.DELETED_SCHEMA)

	}
	
	@Test
	def void testRemoveSchema__TypeMissmatchEnum() {

		parse('''
			rule Rule1 {
						remove enum house.Garage;
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.removeSchema, ErrorCodes.REMOVE_SCHEMA, ErrorMessages.TYPE_MISSMATCH)

	}
	
		@Test
	def void testRemoveSchema__TypeMissmatchError() {

		parse('''
			rule Rule1 {
						remove error house.Garage;
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.removeSchema, ErrorCodes.REMOVE_SCHEMA, ErrorMessages.TYPE_MISSMATCH)

	}
	

	@Test
	def void testRemoveSchema__RenamedSchema() {
		parse('''
			rule Rule1 {
						rename record house.Garage => NewGarage;
						remove record house.Garage;
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.removeSchema, ErrorCodes.REMOVE_SCHEMA, ErrorMessages.DELETED_SCHEMA)
	}

	@Test
	def testRenameSchema__RemovedSchema() {
		parse('''
			rule Rule1 {
						remove record house.Garage;
						rename record house.Garage => NewGarage;
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameSchema, ErrorCodes.RENAME_SCHEMA, ErrorMessages.DELETED_SCHEMA)
	}
	
	@Test
	def testRenameSchema__TypeMissmatch() {
		parse('''
			rule Rule1 {
						rename enum house.Garage => NewGarage;
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameSchema, ErrorCodes.RENAME_SCHEMA, ErrorMessages.TYPE_MISSMATCH)
	}

	/*
	 * NOTE: Renamed objects are treated as if the object has been removed.
	 */
	@Test
	def testRenameSchema__RenameTwice() {
		parse('''
			rule Rule1 {
						rename record house.Garage => NewGarage;
						rename record house.Garage => OldGarage;
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameSchema, ErrorCodes.RENAME_SCHEMA, ErrorMessages.DELETED_SCHEMA)
	}

	@Test
	def testChangeSchema__RemovedSchema() {
		parse('''
			rule Rule1 {
						remove record house.Garage;
						change record house.Garage {};
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeSchema, ErrorCodes.CHANGE_SCHEMA, ErrorMessages.DELETED_SCHEMA)
	}
	
	@Test
	def testChangeSchema__TypeMissmatch() {
		parse('''
			rule Rule1 {
						change error house.Garage {};
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{ }
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeSchema, ErrorCodes.CHANGE_SCHEMA, ErrorMessages.TYPE_MISSMATCH)
	}

	@Test
	def testChangeSchema__RenamedSchema() {
		parse('''
			rule Rule1 {
						rename record house.Garage => NewGarage;
						change record house.Garage {}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeSchema, ErrorCodes.CHANGE_SCHEMA, ErrorMessages.DELETED_SCHEMA)
	}

	@Test
	def testAddRecord__DuplicateSchema() {
		parse('''
			rule Rule1 {
						add.at(0) record house.Garage()
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			] 
		]).assertMethod(AeditPackage.eINSTANCE.addRecord, ErrorCodes.DUPLICATE_FIELD, ErrorMessages.DUPLICATE_SCHEMA)
	}

	@Test
	def testRemoveVariable__DeletedVariable() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							remove num;
							remove num;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.removeVariable, ErrorCodes.REMOVE_VARIABLE, ErrorMessages.DELETED_FIELD)
	}

	@Test
	def testRemoveVariable__RenamedVariable() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							rename num => newNum;
							remove num;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.removeVariable, ErrorCodes.REMOVE_VARIABLE, ErrorMessages.DELETED_FIELD)
	}
	
	@Test
	def testRemoveVariable__IncorrectVariable(){
		parse('''
			rule Rule1 {
						change record house.Garage {
							remove num1;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					record SecondGarage{
						int num1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.removeVariable, ErrorCodes.REMOVE_VARIABLE, ErrorMessages.FIELD_NOT_IN_SCHEMA)
	}

	@Test
	def testRenameVariable__RemovedVariable() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							remove num;
							rename num => newNum;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameVariable, ErrorCodes.RENAME_VARIABLE, ErrorMessages.DELETED_FIELD)
	}

	@Test
	def testRenameVariable__RenamedVariable() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							rename num => newNum;
							rename num => newNum;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameVariable, ErrorCodes.RENAME_VARIABLE, ErrorMessages.DELETED_FIELD)
	}
	
	@Test
	def testRenameVariable__IncorrectVariable() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							rename num1 => newNum;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					record SecondGarage{
						int num1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameVariable, ErrorCodes.RENAME_VARIABLE, ErrorMessages.FIELD_NOT_IN_SCHEMA)
	}
	
	@Test
	def testRenameVariable__NewNameTaken() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							rename num => foo;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
						sting foo;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameVariable, ErrorCodes.DUPLICATE_FIELD, ErrorMessages.DUPLICATE_FIELD)
	}
	

	@Test
	def testChangeType__RemovedVariable() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							remove num;
							set_type num => long;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.CHANGE_TYPE, ErrorMessages.DELETED_FIELD)
	}
	
	@Test
	def testChangeType__IncorrectVariable() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							set_type num1 => long;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					record SecondGarage{
						int num1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.CHANGE_TYPE, ErrorMessages.FIELD_NOT_IN_SCHEMA)
	}

	@Test
	def testChangeDefValue__RemovedVariable() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							remove num;
							set_val num => 1;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.CHANGE_DEF_VALUE, ErrorMessages.DELETED_FIELD)
	}
	
	@Test
	def testChangeDefValue__IncorrectVariable() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							set_val num1 => 1;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					record SecondGarage{
						int num1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.CHANGE_DEF_VALUE, ErrorMessages.FIELD_NOT_IN_SCHEMA)
	}

	@Test
	def testAddVariable_DuplicateField() {
		parse('''
			rule Rule1 {
						change record house.Garage {
							add.at(0) string num;
						}
					}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.addVariable, ErrorCodes.DUPLICATE_FIELD, ErrorMessages.DUPLICATE_FIELD)
	}

	@Test
	def testAddEnumConstant__DuplicateEnumConstant() {
		parse('''
			rule Rule1 {
					change enum house.Colors {
						add.at(0) RED;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
					enum Colors{
						RED, GREEN, BLUE	
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.addEnum, ErrorCodes.DUPLICATE_ENUM_CONST, ErrorMessages.DUPLICATE_ENUM_CONST)
	}

	@Test
	def testRemoveEnumConstant_RemovedEnumConstant() {
		parse('''
			rule Rule1 {
					change enum house.Colors {
						remove RED;
						remove RED;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
					enum Colors{
						RED, GREEN, BLUE	
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.removeEnum, ErrorCodes.REMOVE_ENUM_CONST, ErrorMessages.REMOVED_ENUM_CONST)
	}

	@Test
	def testRemoveEnumConstant__UndefinedEnumConstant() {
		parse('''
			rule Rule1 {
					change enum house.Colors {
						remove PURPLE;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
					enum Colors{
						RED, GREEN, BLUE	
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.removeEnum, ErrorCodes.REMOVE_ENUM_CONST, ErrorMessages.NON_EXISTENT_ENUM_CONST)
	}
	
	@Test
	def testRenameEnumConstant__RemovedEnumConstant(){
		parse('''
			rule Rule1 {
					change enum house.Colors {
						remove RED;
						rename RED => NewPurple;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
					enum Colors{
						RED, GREEN, BLUE	
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameEnum, ErrorCodes.RENAME_ENUM_CONSTANT, ErrorMessages.REMOVED_ENUM_CONST)
	}
	
	@Test
	def testRenameEnumConstant__MissingEnumConstant(){
		parse('''
			rule Rule1 {
					change enum house.Colors {
						rename PURPLE => Green;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
					enum Colors{
						RED, GREEN, BLUE	
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameEnum, ErrorCodes.RENAME_ENUM_CONSTANT, ErrorMessages.NON_EXISTENT_ENUM_CONST)
	}
	
	@Test
	def testRenameEnumConstant_InvalidNewName(){
		parse('''
			rule Rule1 {
					change enum house.Colors {
						rename RED => GREEN;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
					enum Colors{
						RED, GREEN, BLUE	
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.renameEnum, ErrorCodes.DUPLICATE_ENUM_CONST, ErrorMessages.DUPLICATE_ENUM_CONST)
	}

	@Test
	def testChangeDefValue_StringToInt(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => Hello;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.STRING_TO_INT)
	}
	
	@Test
	def testChangeDefValue_FloatToInt(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => 5.5;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.FLOAT_TO_INT)
	}
	
	@Test
	def testChangeDefValue_StringToLong(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => Hello;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						long num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.STRING_TO_LONG)
	}
	
	@Test
	def testChangeDefValue_FloatToLong(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => 5.5;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						long num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.FLOAT_TO_LONG)
	}
	
	@Test
	def testChangeDefValue_FloatToDouble(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => Hello;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						double num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.STRING_TO_DOUBLE)
	}
	
	@Test
	def testChangeDefValue_FloatToString(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => 5.5;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						string num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.FLOAT_TO_STRING)
	}
	
	@Test
	def testChangeDefValue_IntegerToString(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => 1;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						string num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.INTEGER_TO_STRING)
	}
	
	@Test
	def testChangeDefValue_StringToFloat(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => Hello;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						float num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.STRING_TO_FLOAT)
	}
	
	@Test
	def testChangeDefValue__FloatToBoolean(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => 5.5;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						boolean num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.FLOAT_TO_BOOL)
	}
	
	
	
	@Test
	def testChangeDefValue__IntToBoolean(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_val num => 1;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						boolean num;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeDefValue, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.INTEGER_TO_BOOL)
	}
	
	@Test
	def testChangeType__ConvertIntToString(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => string;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num = 1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_INT_TO_STRING)
	}
	
	@Test
	def testChangeType__ConvertIntToInt(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => int;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num = 1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_INT_TO_INT)
	}
	
	@Test
	def testChangeType__ConvertIntToBool(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => boolean;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						int num = 1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_INT_TO_BOOL)
	}
	
	@Test
	def testChangeType__ConvertLongToInt(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => int;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						long num = 1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_LONG_TO_INT)
	}
	
	@Test
	def testChangeType__ConvertLongToString(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => string;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						long num = 1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_LONG_TO_STRING)
	}
	
	@Test
	def testChangeType__ConvertLongToDouble(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => double;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						long num = 1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_LONG_TO_DOUBLE)
	}
	
	@Test
	def testChangeType__ConvertLongToLong(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => long;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						long num = 1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_LONG_TO_LONG)
	}
	
	@Test
	def testChangeType__ConvertLongToBool(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => boolean;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						long num = 1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_LONG_TO_BOOL)
	}
	
	@Test
	def testChangeType__ConvertDoubleToBool(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => boolean;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						double num = 1.1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_DOUBLE_TO_BOOL)
	}
	
	@Test
	def testChangeType__ConvertDoubleToString(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => string;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						double num = 1.1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_DOUBLE_TO_STRING)
	}
	
	@Test
	def testChangeType__ConvertDoubleToDouble(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => double;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						double num = 1.1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_DOUBLE_TO_DOUBLE)
	}
	
	@Test
	def testChangeType__ConvertDoubleToInteger(){
		parse('''
			rule Rule1 {
					change record house.Garage {
						set_type num => int;
					}
				}
		''', URI.createFileURI("/Main.aedit"), rsp.get => [
			createResource(URI.createFileURI("/Other.avdl")) => [
				load(new StringInputStream('''
				@namespace('house')
				protocol House{
					record Garage{
						double num = 1.1;
					}
					
				}''', "UTF-8"), null)
			]
		]).assertMethod(AeditPackage.eINSTANCE.changeType, ErrorCodes.TYPE_MISSMATCH, ErrorMessages.CONVERT_DOUBLE_TO_INT)
	}
	
	
	def private assertMethod(Model m, EClass model, String code, String message) {
		m.assertError(
			model,
			code,
			message
		)
	}
}
