/**
 * generated by Xtext 2.12.0
 */
package org.aedit.ui;

import org.aedit.ui.AbstractAeditUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AeditUiModule extends AbstractAeditUiModule {
  public AeditUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
